POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZtYXJ0dGlsIiwiaWQiOiI1ZTRhOTNlYzdhYmZjNzE5ZDAyNjU4YWUiLCJpYXQiOjE1ODE5NjYxNDl9.lnfrMOoMNheWXrIy9jgYr9LNd-4xRqP1M3HqzP-BuzU

{
    "title": "Does this blog get added to the database?",    
    "author": "Inquiring Minds",
    "url": "http://www.testaddress.com/blogauthorized4",
    "likes": 10
}